[2024-04-29T16:36:29.852+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T16:36:29.872+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.validate_file manual__2024-04-29T16:36:00.267671+00:00 [queued]>
[2024-04-29T16:36:29.880+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.validate_file manual__2024-04-29T16:36:00.267671+00:00 [queued]>
[2024-04-29T16:36:29.880+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T16:36:29.893+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): validate_file> on 2024-04-29 16:36:00.267671+00:00
[2024-04-29T16:36:29.899+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T16:36:29.900+0000] {standard_task_runner.py:63} INFO - Started process 177 to run task
[2024-04-29T16:36:29.900+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'validate_file', 'manual__2024-04-29T16:36:00.267671+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_cab.py', '--cfg-path', '/tmp/tmpeu1epdz1']
[2024-04-29T16:36:29.903+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask validate_file
[2024-04-29T16:36:29.945+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.validate_file manual__2024-04-29T16:36:00.267671+00:00 [running]> on host 619702048a97
[2024-04-29T16:36:30.025+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='validate_file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T16:36:00.267671+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T16:36:00.267671+00:00'
[2024-04-29T16:36:30.028+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T16:36:30.040+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-29T16:36:30.042+0000] {logging_mixin.py:188} INFO - debug
[2024-04-29T16:36:30.042+0000] {logging_mixin.py:188} INFO - None
[2024-04-29T16:36:30.043+0000] {python.py:237} INFO - Done. Returned value was: file_exception
[2024-04-29T16:36:30.043+0000] {branch.py:36} INFO - Branch into file_exception
[2024-04-29T16:36:30.044+0000] {skipmixin.py:178} INFO - Following branch file_exception
[2024-04-29T16:36:30.057+0000] {skipmixin.py:246} INFO - Skipping tasks [('load_stage', -1)]
[2024-04-29T16:36:30.077+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T16:36:30.093+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_yellow_cab, task_id=validate_file, execution_date=20240429T163600, start_date=20240429T163629, end_date=20240429T163630
[2024-04-29T16:36:30.123+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T16:36:30.136+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
  result = cls.__new__(cls)

[2024-04-29T16:36:30.165+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T16:36:30.168+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
